### ISSUE TITLE
wget error

### ISSUE THREAD

**Issue by GhostRider5666** [iamromulan/quectel-rgmii-toolkit#14]
Resolving raw.githubusercontent.com... failed: Temporary failure in name resolution.
wget: unable to resolve host address 'raw.githubusercontent.com'

**Comment by iamromulan** [comment]
Is the modem able to reach the internet? 
Is it a problem resolving hostnames, IP addresses, or both?
within the modems shell see if you can reach google. Try ping google.com and ping 8.8.8.8
Ctrl-C should stop the ping

**Comment by GhostRider5666** [comment]
Yes, I can do all of that?

**Comment by iamromulan** [comment]
If you indeed have Internet connectivity and can reach both 8.8.8.8 and google.com via ping that rules out any DNS issues.

Perhaps there really was some sort of temporary issue. 

Also I forgot to ask, is that error as result of trying to install something from the toolkit or trying to run the toolkit in general?

Within the modems shell try running this again, it may very well have been a temporary issue:
cd /tmp && wget -O RMxxx_rgmii_toolkit.sh https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/main/RMxxx_rgmii_toolkit.sh && chmod +x RMxxx_rgmii_toolkit.sh && ./RMxxx_rgmii_toolkit.sh && cd /

**Comment by GhostRider5666** [comment]
I get the same thing after running adb shell?

**Comment by GhostRider5666** [comment]
![Screenshot 2024-03-20 145946](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/96890367/ab7eb987-192f-42ef-b761-8114a5c09eeb)

**Comment by iamromulan** [comment]
Run the AT command AT+QMAPWAC?
What number does it respond with?

**Comment by iamromulan** [comment]
> ![Screenshot 2024-03-20 145946](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/96890367/ab7eb987-192f-42ef-b761-8114a5c09eeb)
> 

Are you available on a private message platform? It's very odd that you can reach other sites but not GitHub. I'm willing to provide remote support to diagnose. Just download AnyDesk and have the modem connected by USB and give me the AnyDesk code. You'll want to private message me that though.

**Comment by GhostRider5666** [comment]
Facebook?

**Comment by iamromulan** [comment]
> Facebook?
> 

https://www.facebook.com/share/9rJNcaSKmsftfxcL/?mibextid=qi2Omg

**Comment by iamromulan** [comment]
Issue solved by flashing firmware.
Tailscale messed with the resolv.conf file causing DNS issues.

Tailscale install process patched to prevent this in the future.
