### ISSUE TITLE
ERROR: could not open HSTS store at '/home/root/.wget-hsts'. HSTS will be disabled.

### ISSUE THREAD

**Issue by suntecpro101** [iamromulan/quectel-rgmii-toolkit#15]
When I Run the toolkit I see this error, is that normal?

C:\Program Files (x86)\ADB and Fastboot++>adb shell wget -P /tmp https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/main/RMxxx_rgmii_toolkit.sh
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/root/.wget-hsts'. HSTS will be disabled.
--2024-03-20 19:31:21--  https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/main/RMxxx_rgmii_toolkit.sh
Resolving raw.githubusercontent.com... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 42387 (41K) [text/plain]
Saving to: '/tmp/RMxxx_rgmii_toolkit.sh'

RMxxx_rgmii_toolkit 100%[===================>]  41.39K  --.-KB/s    in 0.02s

2024-03-20 19:31:22 (2.13 MB/s) - '/tmp/RMxxx_rgmii_toolkit.sh' saved [42387/42387]

C:\Program Files (x86)\ADB and Fastboot++>adb shell chmod +x /tmp/RMxxx_rgmii_toolkit.sh

C:\Program Files (x86)\ADB and Fastboot++>adb shell sh /tmp/RMxxx_rgmii_toolkit.sh[5g LOG.txt]

please look at this log file for more Details

I'm Using RM520 

(https://github.com/iamromulan/quectel-rgmii-toolkit/files/14671858/5g.LOG.txt)

**Comment by iamromulan** [comment]
https://superuser.com/questions/1539972/wget-error-bash-windows-subsystem-for-linux

"HSTS is an optional security measurement on top on HTTPS. As the HTTPS connection itself works and the file has been downloaded this seems to be rather a warning than an error."
