### ISSUE TITLE
HSTS

### ISSUE THREAD

**Issue by smashrvmco** [iamromulan/quectel-rgmii-toolkit#28]
I get the following error when running the script.. doesnt seem to affect anything from not working. On my rm521f-gl this is mounted in a read-only format:

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/root/.wget-hsts'. HSTS will be disabled.

Just wondering if I set something up wrong that could cause problems later down the road, or if this is expected behavior for now 

Edit: This was communicating via adb over USB cable. Using TTYd, I didnt get this error, but I did notice another just now using the development branch:
Adding AT Socat Bridge systemd service units...
AT Socat Bridge service online: smd11 to ttyOUT
Job for socat-killsmd7bridge.service failed because the control process exited with error code.
See "systemctl status socat-killsmd7bridge.service" and "journalctl -xe" for details.
AT Socat Bridge service online: smd7 to ttyOUT2
AT Socat Bridge services Installed!
Failed to stop simplefirewall.service: Unit simplefirewall.service not loaded.
Failed to stop ttl-override.service: Unit ttl-override.service not loaded.

**Comment by dr-dolomite** [comment]
Those were completely fine afaik. If something went wrong, just use the script again to remove the installation, do a reboot and then install again.

**Comment by iamromulan** [comment]
> Will not apply HSTS. The HSTS database must be a regular and non-world-writable file

https://superuser.com/a/1540028



> Failed to stop simplefirewall.service: Unit simplefirewall.service not loaded.
> Failed to stop ttl-override.service: Unit ttl-override.service not loaded.

These are ok
