### ISSUE TITLE
Feat: SMS send/receive

### ISSUE THREAD

**Issue by alexlearncss** [iamromulan/quectel-rgmii-toolkit#3]
Do you have sms send and receive ?

**Comment by iamromulan** [comment]
Not yet. Maybe eventually :)
If you want to add it feel free to PR

**Comment by alexlearncss** [comment]
![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/90631770/179ef12a-591b-42e2-b3ee-6dd800870bee)

Like this bro , look at nav bar

**Comment by iamromulan** [comment]
Wow!! Would love to have a look at the code for that!

**Comment by chienlananh** [comment]
You can add SMS available
