### ISSUE TITLE
Request to Update Development README Images

### ISSUE THREAD

**Issue by dr-dolomite** [iamromulan/quectel-rgmii-toolkit#47]
Only if you have free time of course 😆

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/044a2855-ab4a-44cb-beb4-65669b2ccde9)

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/8ac98aa9-8f4d-40a2-962b-cac1ef3da89d)

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/7d958ec5-d05b-45d1-9336-d8f06b9f11a5)

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/ab5024a3-d37c-4599-bc00-d6da1a58cd62)

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/8a2ac73a-5f25-4b05-95c0-b0e12732c046)

**Comment by iamromulan** [comment]
Will do soon! :)
