### ISSUE TITLE
Development: Console and Tailscale Issues

### ISSUE THREAD

**Issue by dr-dolomite** [iamromulan/quectel-rgmii-toolkit#49]
Even after reflash, the console page doesn't work on my end.

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/561964ec-2d61-47e0-80d6-bb8360250fcf)

Also, I can't configure tailscale using the install script.

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/07738eb1-e56a-4d22-9216-97013c948734)

**Comment by iamromulan** [comment]
Oh whoops; tailscale config should be fixed: https://github.com/iamromulan/quectel-rgmii-toolkit/commit/b89145e9e4071f8c1a49956f3c4254ec328c5055

Run ``systemctl status ttyd`` for me
