### ISSUE TITLE
Feat: Automatic Band Selection based on latency

### ISSUE THREAD

**Issue by danry25** [iamromulan/quectel-rgmii-toolkit#54]
Occasionally I run into these modems doing fun things like aggregating congested LTE Band 12 with LTE Band 2 and 5G N41 causing 250ms to 500ms latency spikes (whereas most traffic only experiences 20ms to 30ms of latency).

It would be handy to have a watchdog that runs a ping to 1.1.1.1, and when this latency exceeds a certain boundary (say 100ms) remove the band that is problematic from the list of allowed LTE, 5G-NSA and 5G-SA bands.

**Comment by dr-dolomite** [comment]
Thats quite hard to implement since different Module versions (even variants) have different support for CA band combinations. But Ill try my best to create a similar approach on the Simple Watchcat.

**Comment by iamromulan** [comment]
The next question is how would we determine what the "problematic" band is? Order of operations for removing bands? Re-ping, repeat?
