### ISSUE TITLE
IP Passthrough 

### ISSUE THREAD

**Issue by dr-dolomite** [iamromulan/quectel-rgmii-toolkit#7]
Good day! I just want to ask if it is possible to bridge the modem to router without the traffic being routed to 192.168.225.1? Im using IPPT and tracert shows that it still making my router behind NAT. I want to use GL inet's DDNS and it requires a direct public ip address and even though the dashboard shows my public ip address, it still doesnt work. Thanks!

![image](https://github.com/iamromulan/quectel-rgmii-toolkit/assets/73575327/df436ee6-0c79-4dc9-9265-3d6b4fffefc7)

**Comment by iamromulan** [comment]
Hello there!
If you are getting assigned a public IP directly disable IPPT Nat. 

The way I look at it these modems have "3 stages of IP Passthrough"
First being the DMZ method
Then the MPDN rule
Finally true IPPT mode. 
Refer to this section
https://github.com/iamromulan/quectel-rgmii-configuration-notes?tab=readme-ov-file#disable-nat-to-vlan

Note that you will loose local network access to the gateway IP/simpleadmin/servers on the modem.

You can use Tailscale to get around that limitation.

**Comment by dr-dolomite** [comment]
I see but Im not that confident messing with module configs right now especially since I cannot fully understand all of it despite reading the documentations. For now, I applied the DDNS patch for GL devices behind NAT. Thanks for this still. Cheers!
