### ISSUE TITLE
wget has been removed

### ISSUE THREAD

**Issue by andrewwm** [iamromulan/quectel-rgmii-toolkit#71]
I have a RM500Q-AE and I just updated it to firmware version RM500QAEAAR13A03M4G_01.203.01.203. Following the directions to reinstall the simple admin page, it looks like wget has been removed with this firmware update. I looked around the system files to see if the binary is somewhere else, but I couldn't find it. I also looked at busybox and it looks like wget is not included. Good news is that curl is still available, and I was able to get to download and run the main script using this command

`cd /tmp && curl -o RMxxx_rgmii_toolkit.sh https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/main/RMxxx_rgmii_toolkit.sh && chmod +x RMxxx_rgmii_toolkit.sh && ./RMxxx_rgmii_toolkit.sh && cd /`

but it fails to install simple admin because it calls wget.

**Comment by iamromulan** [comment]
Yeah with the changes they have been making I have been slowly moving toward using curl instead. There are scenarios where both are available, or only one is available. I'll have to try and adapt all the installer scripts to handle any scenario.
