### ISSUE TITLE
Tailscale no longer downloads wget gets an error.

### ISSUE THREAD

**Issue by Snake98bm** [iamromulan/quectel-rgmii-toolkit#74]
wget fails to download tailscale

` wget https://pkgs.tailscale.com/stable/tailscale_1.62.1_arm
.tgz
Connecting to pkgs.tailscale.com (199.38.181.239:443)
wget: note: TLS certificate validation not implemented
Connecting to dl.tailscale.com (109.105.218.17:443)
wget: got bad TLS record (len:0) while expecting handshake record
wget: error getting response: Connection reset by peer
/usrdata/tailscale #`
wget: got bad TLS record (len:0) while expecting handshake record
wget: error getting response: Connection reset by peer

I changed it to curl and it works fine
curl  https://pkgs.tailscale.com/stable/tailscale_1.62.1_arm.tgz --output tailscale_1.62.1_arm.tgz

**Comment by iamromulan** [comment]
I am making a download executable that will be able to use curl and wget based on whats available. For now please use the correct branches for your platform and there shouldn't be an issue.
