### ISSUE TITLE
Not enough storage to install anything on RM551

### ISSUE THREAD

**Issue by xBryan101** [iamromulan/quectel-rgmii-toolkit#78]
Just got a new RM551 that came running the latest non-beta firmware.
I noticed the root partition is small, only like 100MB with about 55MB in use already before doing anything.

I found I can't actually install or do anything with the scripts because the lack of space. It will download the gzip but can't extract them as runs out of storage..
I'm wondering if the partition sizes are different on these newer releases or what the work around may be? I noticed it has two temp partitions and one is like 256MB with 0 used.

Here is sizes after trying to install the scripts, as you can see it results in the root not having much space left and thus fails to extract and work. 
ubi0:rootfs          ubifs         102372     78712     23660  77% /
tmpfs                tmpfs         287972       400    287572   0% /tmp
tmpfs                tmpfs            512         0       512   0% /dev
/dev/ubi1_0          ubifs          88844     82280      6564  93% /firmware
ubi0:persist         ubifs           2328       656      1484  31% /persist
ubi0:cachefs         ubifs          10724       260      9856   3% /cache
ubi0:systemrw        ubifs           2328       468      1672  22% /overlay
/dev/ubi0_1          ubifs         322972       336    322636   0% /data
overlay              overlay         2328       468      1672  22% /etc

I am not sure what the partitions look like on the other firmware/older cards out in the wild and if something changed so any insight would be grateful.

Sample failure log:
Installing Tailscale...
Creating /usrdata/tailscale/
Downloading binary files...
Downloading 'https://pkgs.tailscale.com/stable/tailscale_1.62.1_arm.tgz'
Connecting to 2607:f740:f::d19:443
Writing to 'tailscale_1.62.1_arm.tgz'
tailscale_1.62.1_arm 100% |*******************************| 24509k  0:00:00 ETA
Download completed (25097898 bytes)
tar: write error: No space left on device
tar: write: Broken pipe
mv: can't rename 'tailscale': No space left on device
mv: can't rename 'tailscaled': No space left on device

**Comment by iamromulan** [comment]
Flash firmware start from scratch
Use option 2 in the SDXPINN toolkit
https://github.com/iamromulan/quectel-rgmii-toolkit/tree/SDXPINN

In the development-SDXPINN branch I've turned the mount-fix into an ipk

Source with build file:
https://github.com/iamromulan/quectel-rgmii-toolkit/tree/development-SDXPINN/ipk-source/sdxpinn-mount-fix

IPK (requires an internet connection at this time for post install dependencies) 
https://github.com/iamromulan/quectel-rgmii-toolkit/blob/development-SDXPINN/ipk/sdxpinn-mount-fix_1.0_aarch64_cortex-a53.ipk
